Use ad hoc shell code rather than run-test-suites.pl to run groups
This way we get a verbose report from the test suites and no noise from
skipped suites. Also, this way, the code doesn't depend on the exact way
run-test-suites.pl interpolates the --skip option into a regex.

Signed-off-by: Gilles Peskine <Gilles.Peskine@arm.com>

diff --git a/tools/bin/mbedtls-prepare-build b/tools/bin/mbedtls-prepare-build
--- a/tools/bin/mbedtls-prepare-build
+++ b/tools/bin/mbedtls-prepare-build
@@ -463,7 +463,7 @@ class MakefileMaker:
         for com in commands:
             self.format('\t{}{}',
                         ('' if short is None else '$(Q)'),
-                        com.replace('\n', ' \\\n\t'))
+                        com.strip('\n').replace('\n', ' \\\n\t'))
         if help is not None:
             self.help[name] = help
         if phony:
@@ -1115,9 +1115,13 @@ class MakefileMaker:
         """
         use_run_test_suites = False
         for base, executables in groups.items():
-            short_base = re.sub(r'\Atest_suite_', r'', base)
-            skip_re = '(?!{})[A-Za-z_0-9]+'.format(short_base)
-            shell_code = '$(PERL) scripts/run-test-suites.pl --skip=\'{}\''.format(skip_re)
+            shell_code = '''
+failures=;
+for x in {}; do
+./$$x || failures="$$failures $$x";
+done;
+if [ -n "$$failures" ]; then echo; echo "Failures:$$failures"; false; fi
+'''.format(' '.join([re.sub(r'.*/', r'', exe) for exe in executables]))
             self.target('tests/' + base + '.run',
                         groups[base] + ['tests/seedfile'],
                         ['$(SETENV)cd tests && ' + shell_code],
